// examples/vue/src/ModalOne.vue
<script setup lang="ts">
import { lock, unlock } from 'tua-body-scroll-lock'
import { ref, watch } from 'vue'

const props = defineProps<{ visible: boolean }>()
const emits = defineEmits<{(e: 'clickBtn'): void, (e: 'update:visible', v: boolean): void}>()

const targetOneRef = ref<HTMLElement>()
const targetTwoRef = ref<HTMLElement>()

watch(() => props.visible, () => {
  if (props.visible) {
    lock(
      [targetOneRef.value!, targetTwoRef.value!],
      { overflowType: 'clip', useGlobalLockState: true },
    )
  } else {
    unlock(
      [targetOneRef.value!, targetTwoRef.value!],
      { useGlobalLockState: true },
    )
  }
})

</script>

<template>
  <div class="modal" v-show="props.visible" @click="emits('update:visible', false)">
    <h2>
      dialog one
      <button @click.stop="emits('clickBtn')">click me to show dialog two</button>
    </h2>

    <div id="targetOne" ref="targetOneRef" class="target" @click.stop>
      <p v-for="i in 50" :key="i">{{i}} scroll me~</p>
    </div>

    <div id="targetTwo" ref="targetTwoRef" class="target" @click.stop>
      <p v-for="i in 50" :key="i">{{i}} scroll me~</p>
    </div>
  </div>
</template>

<style scoped>

#targetOne {
  height: 30%;

  color: blue;
  border-bottom: 1px dashed black;
}

#targetTwo {
  height: 30%;

  color: red;
}

</style>

// examples/react/src/ModalOne.tsx
import { useEffect, useRef } from 'react'
import { lock, unlock } from 'tua-body-scroll-lock'

export function ModalOne (props: {
  onClose: () => void
  onClickBtn: () => void
}) {
  const targetOneRef = useRef<HTMLDivElement>(null)
  const targetTwoRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    lock(
      [targetOneRef.current!, targetTwoRef.current!],
      { overflowType: 'clip', useGlobalLockState: true },
    )
    return () => {
      unlock(
        [targetOneRef.current!, targetTwoRef.current!],
        { useGlobalLockState: true },
      )
    }
  }, [])

  return (
    <div id="modalOne" className="modal" onClick={props.onClose}>
      <h2>
        dialog one
        <button onClick={e => {
          props.onClickBtn()
          e.stopPropagation()
        }}>
          click me to show dialog two
        </button>
      </h2>

      <div id="targetOne" ref={targetOneRef} className="target" onClick={e => e.stopPropagation()}>
        { Array(50).fill(0).map((_, i) => <p key={i}>{i} scroll me~</p>) }
      </div>

      <div id="targetTwo" ref={targetTwoRef} className="target" onClick={e => e.stopPropagation()}>
        { Array(50).fill(0).map((_, i) => <p key={i}>{i} scroll me~</p>) }
      </div>
    </div>
  )
}
